from pathlib import Path

paths = [
    Path(r'c:\xampp\htdocs\Hesabat\ui\assets\index-CC2b_5k0.js'),
    Path(r'c:\xampp\htdocs\Hesabat\deploy_hesabat_root\assets\index-CC2b_5k0.js'),
]

for path in paths:
    s = path.read_text(encoding='utf-8')

    old_state = 'ue=S.useMemo(()=>{const h={},b=A=>String(A??"").trim().toLowerCase(),_=new Map,W=new Set(["konica","roland","laser"]);for(const A of N){const V=b(A==null?void 0:A.price_key),F=b(A==null?void 0:A.name),U=V||F;if(!U)continue;V&&_.set(V,U),F&&_.set(F,U)}for(const A of N){const V=b(A==null?void 0:A.price_key),F=b(A==null?void 0:A.name),U=V||F;if(!U)continue;const Y=ne[U]||ne[F]||ne[V]||new Set,Z=w.filter(q=>{const we=b(q==null?void 0:q.category),bi=_.get(we)||we,Qi=String((q==null?void 0:q.key)??"");return bi===U&&(!W.has(U)||!Y.has(Qi))});Z.length>0&&(h[U]={name:String((A==null?void 0:A.name)??U),materials:Z,tone:F==="konica"||U==="konica"?"indigo":F==="roland"||U==="roland"?"orange":F==="laser"||U==="laser"?"teal":String((A==null?void 0:A.name)??U).length%3===0?"indigo":String((A==null?void 0:A.name)??U).length%3===1?"orange":"teal"})}return h},[N,w,ne]);'
    new_state = 'ue=S.useMemo(()=>{const h={},b=A=>String(A??"").trim().toLowerCase(),_=new Map,W=new Set(["konica","roland","laser"]);for(const A of N){const V=b(A==null?void 0:A.price_key),F=b(A==null?void 0:A.name),U=V||F;if(!U)continue;V&&_.set(V,U),F&&_.set(F,U)}for(const A of N){const V=b(A==null?void 0:A.price_key),F=b(A==null?void 0:A.name),U=V||F;if(!U)continue;const Y=ne[U]||ne[F]||ne[V]||new Set,Z=w.filter(q=>{const we=b(q==null?void 0:q.category),bi=_.get(we)||we,Qi=String((q==null?void 0:q.key)??"");return bi===U&&(!W.has(U)||!Y.has(Qi))});Z.length>0&&(h[U]={name:String((A==null?void 0:A.name)??U),materials:Z,tone:F==="konica"||U==="konica"?"indigo":F==="roland"||U==="roland"?"orange":F==="laser"||U==="laser"?"teal":String((A==null?void 0:A.name)??U).length%3===0?"indigo":String((A==null?void 0:A.name)??U).length%3===1?"orange":"teal"})}return h},[N,w,ne]),he=ue.konica&&Array.isArray(ue.konica.materials)?ue.konica.materials:[],be=ue.roland&&Array.isArray(ue.roland.materials)?ue.roland.materials:[],_e=ue.laser&&Array.isArray(ue.laser.materials)?ue.laser.materials:[];'
    if old_state not in s:
        raise SystemExit(f'state target not found in {path}')
    s = s.replace(old_state, new_state, 1)

    old_konica = 'o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-5",children:[o.jsx(z,{label:"Backleed",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_backleed,onChange:h=>g("konica_backleed",h.target.value)}),o.jsx(z,{label:"Flex",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_flax,onChange:h=>g("konica_flax",h.target.value)}),o.jsx(z,{label:"Banner 440 GR White",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_banner_404_white,onChange:h=>g("konica_banner_404_white",h.target.value)}),o.jsx(z,{label:"Banner 440 GR Black",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_banner_440_black,onChange:h=>g("konica_banner_440_black",h.target.value)})]})]}),o.jsxs("div",{className:"bg-slate-50/50 p-6 rounded-3xl border border-slate-100",children:[o.jsxs("h3",{className:"text-base font-bold text-orange-900 mb-6 flex items-center gap-2",children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-orange-500"}),"Roland"]})'
    new_konica = 'o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-5",children:[o.jsx(z,{label:"Backleed",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_backleed,onChange:h=>g("konica_backleed",h.target.value)}),o.jsx(z,{label:"Flex",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_flax,onChange:h=>g("konica_flax",h.target.value)}),o.jsx(z,{label:"Banner 440 GR White",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_banner_404_white,onChange:h=>g("konica_banner_404_white",h.target.value)}),o.jsx(z,{label:"Banner 440 GR Black",placeholder:"Qiymət",inputMode:"decimal",value:e.konica_banner_440_black,onChange:h=>g("konica_banner_440_black",h.target.value)})]}),he.length>0&&o.jsx("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-5 mt-5",children:he.map(h=>o.jsx(z,{label:String(h.label??"").replace(/[_-]+/g," ").replace(/\\b\\w/g,b=>b.toUpperCase()),placeholder:"Qiymət",inputMode:"decimal",value:((e.prices||{}).konica||{})[h.key]??"",onChange:b=>pe("konica",h.key,b.target.value)},`konica-${h.key}`))})]}),o.jsxs("div",{className:"bg-slate-50/50 p-6 rounded-3xl border border-slate-100",children:[o.jsxs("h3",{className:"text-base font-bold text-orange-900 mb-6 flex items-center gap-2",children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-orange-500"}),"Roland"]})'
    if old_konica not in s:
        raise SystemExit(f'konica target not found in {path}')
    s = s.replace(old_konica, new_konica, 1)

    old_roland = 'o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-2 gap-5",children:[o.jsx(z,{label:"Banner Black Matt",placeholder:"Qiymət",inputMode:"decimal",value:e.roland_black_matt,onChange:h=>g("roland_black_matt",h.target.value)}),o.jsx(z,{label:"Banner Black Glossy",placeholder:"Qiymət",inputMode:"decimal",value:e.roland_black_glossy,onChange:h=>g("roland_black_glossy",h.target.value)})]})]}),o.jsxs("div",{className:"bg-slate-50/50 p-6 rounded-3xl border border-slate-100",children:[o.jsxs("h3",{className:"text-base font-bold text-teal-900 mb-6 flex items-center gap-2",children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-teal-500"}),"Laser Cutter"]})'
    new_roland = 'o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-2 gap-5",children:[o.jsx(z,{label:"Banner Black Matt",placeholder:"Qiymət",inputMode:"decimal",value:e.roland_black_matt,onChange:h=>g("roland_black_matt",h.target.value)}),o.jsx(z,{label:"Banner Black Glossy",placeholder:"Qiymət",inputMode:"decimal",value:e.roland_black_glossy,onChange:h=>g("roland_black_glossy",h.target.value)})]}),be.length>0&&o.jsx("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-5 mt-5",children:be.map(h=>o.jsx(z,{label:String(h.label??"").replace(/[_-]+/g," ").replace(/\\b\\w/g,b=>b.toUpperCase()),placeholder:"Qiymət",inputMode:"decimal",value:((e.prices||{}).roland||{})[h.key]??"",onChange:b=>pe("roland",h.key,b.target.value)},`roland-${h.key}`))})]}),o.jsxs("div",{className:"bg-slate-50/50 p-6 rounded-3xl border border-slate-100",children:[o.jsxs("h3",{className:"text-base font-bold text-teal-900 mb-6 flex items-center gap-2",children:[o.jsx("span",{className:"w-2 h-2 rounded-full bg-teal-500"}),"Laser Cutter"]})'
    if old_roland not in s:
        raise SystemExit(f'roland target not found in {path}')
    s = s.replace(old_roland, new_roland, 1)

    old_laser = 'o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-2 gap-5",children:[o.jsx(z,{label:"Graw Cut On Forex",placeholder:"Qiymət",inputMode:"decimal",value:e.laser_graw_cut_forex,onChange:h=>g("laser_graw_cut_forex",h.target.value)}),o.jsx(z,{label:"Graw Cut On Orch",placeholder:"Qiymət",inputMode:"decimal",value:e.laser_graw_cut_orch,onChange:h=>g("laser_graw_cut_orch",h.target.value)})]})]}),Object.keys(ue).length>0&&o.jsx("div",{className:"space-y-6",children:Object.entries(ue).map(([h,b])=>o.jsxs("div",{className:"bg-slate-50/50 p-6 rounded-3xl border border-slate-100",children:[o.jsxs("h3",{className:`text-base font-bold ${b.tone==="orange"?"text-orange-900":b.tone==="teal"?"text-teal-900":"text-indigo-900"} mb-6 flex items-center gap-2`,children:[o.jsx("span",{className:`w-2 h-2 rounded-full ${b.tone==="orange"?"bg-orange-500":b.tone==="teal"?"bg-teal-500":"bg-indigo-500"}`}),b.name==="Laser"?"Laser Cutter":b.name]}),o.jsx("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-5",children:b.materials.map(_=>o.jsx(z,{label:String(_.label??"").replace(/[_-]+/g," ").replace(/\\b\\w/g,E=>E.toUpperCase()),placeholder:"Qiymət",inputMode:"decimal",value:((e.prices||{})[h]||{})[_.key]??"",onChange:E=>pe(h,_.key,E.target.value)},`${h}-${_.key}`))})]},h))}),o.jsx("div",{className:"pt-4 flex justify-end",children:o.jsx(fe,{size:"lg",className:"px-10",type:"submit",disabled:s,children:"Əlavə et"})})'
    new_laser = 'o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-2 gap-5",children:[o.jsx(z,{label:"Graw Cut On Forex",placeholder:"Qiymət",inputMode:"decimal",value:e.laser_graw_cut_forex,onChange:h=>g("laser_graw_cut_forex",h.target.value)}),o.jsx(z,{label:"Graw Cut On Orch",placeholder:"Qiymət",inputMode:"decimal",value:e.laser_graw_cut_orch,onChange:h=>g("laser_graw_cut_orch",h.target.value)})]}),_e.length>0&&o.jsx("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-5 mt-5",children:_e.map(h=>o.jsx(z,{label:String(h.label??"").replace(/[_-]+/g," ").replace(/\\b\\w/g,b=>b.toUpperCase()),placeholder:"Qiymət",inputMode:"decimal",value:((e.prices||{}).laser||{})[h.key]??"",onChange:b=>pe("laser",h.key,b.target.value)},`laser-${h.key}`))})]}),Object.keys(ue).length>0&&o.jsx("div",{className:"space-y-6",children:Object.entries(ue).filter(([h])=>!["konica","roland","laser"].includes(h)).map(([h,b])=>o.jsxs("div",{className:"bg-slate-50/50 p-6 rounded-3xl border border-slate-100",children:[o.jsxs("h3",{className:`text-base font-bold ${b.tone==="orange"?"text-orange-900":b.tone==="teal"?"text-teal-900":"text-indigo-900"} mb-6 flex items-center gap-2`,children:[o.jsx("span",{className:`w-2 h-2 rounded-full ${b.tone==="orange"?"bg-orange-500":b.tone==="teal"?"bg-teal-500":"bg-indigo-500"}`}),b.name==="Laser"?"Laser Cutter":b.name]}),o.jsx("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-5",children:b.materials.map(_=>o.jsx(z,{label:String(_.label??"").replace(/[_-]+/g," ").replace(/\\b\\w/g,E=>E.toUpperCase()),placeholder:"Qiymət",inputMode:"decimal",value:((e.prices||{})[h]||{})[_.key]??"",onChange:E=>pe(h,_.key,E.target.value)},`${h}-${_.key}`))})]},h))}),o.jsx("div",{className:"pt-4 flex justify-end",children:o.jsx(fe,{size:"lg",className:"px-10",type:"submit",disabled:s,children:"Əlavə et"})})'
    if old_laser not in s:
        raise SystemExit(f'laser target not found in {path}')
    s = s.replace(old_laser, new_laser, 1)

    path.write_text(s, encoding='utf-8')
    print(f'patched {path}')
