from pathlib import Path

paths = [
    r'c:\xampp\htdocs\Hesabat\ui\assets\index-CC2b_5k0.js',
    r'c:\xampp\htdocs\Hesabat\deploy_hesabat_root\assets\index-CC2b_5k0.js',
]

old = 'o.jsxs(Pt,{className:"p-6",children:[o.jsxs("div",{className:"mb-6 rounded-2xl border-2 border-dashed border-violet-200 bg-violet-50/40 px-5 py-4",children:[o.jsx("div",{className:"text-sm font-bold text-violet-700 mb-1",children:"Yeni material yarat"}),o.jsx("div",{className:"text-xs font-medium text-slate-500",children:"Bu hissədə yeni material yarada və sonra printerlərə əlavə edə bilərsiniz."})]}),o.jsx("div",{className:"font-bold text-slate-900 mb-4",children:"Yeni material"}),o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-4",children:[o.jsxs("div",{children:[o.jsx("div",{className:"text-sm font-bold text-slate-700 mb-2",children:"Mövcud material seç"}),o.jsxs("select",{className:"w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700",value:R,onChange:T=>{const N=T.target.value,L=p.find(w=>String((w==null?void 0:w.key)??"")===N);H(N),J(String((L==null?void 0:L.label)??""))},children:[o.jsx("option",{value:"",children:"Material seç"}),Array.from(new Map(p.map(T=>[String((T==null?void 0:T.key)??""),T]).filter(T=>T[0])) .values()).map(T=>o.jsx("option",{value:T.key,children:T.label||T.key},T.key))]})]}),o.jsx(z,{label:"key (məs: banner_matt)",value:R,onChange:T=>H(T.target.value)}),o.jsx(z,{label:"label",value:W,onChange:T=>J(T.target.value)}),o.jsxs("div",{className:"md:col-span-2",children:[o.jsx("div",{className:"text-sm font-bold text-slate-700 mb-2",children:"Printer seç"}),o.jsx("div",{className:"rounded-2xl border border-gray-200 bg-white px-4 py-3 max-h-48 overflow-y-auto space-y-2",children:d.filter(T=>Number((T==null?void 0:T.status)??1)===1).map(T=>{const N=String((T==null?void 0:T.price_key)??"").trim()||String((T==null?void 0:T.name)??"").trim();return o.jsxs("label",{className:"flex items-center gap-2 text-sm font-semibold text-slate-700",children:[o.jsx("input",{type:"checkbox",checked:ce.includes(N),onChange:L=>ee(w=>L.target.checked?w.includes(N)?w:[...w,N]:w.filter(O=>O!==N))}),o.jsx("span",{children:T.name})]},T.id)})})]}),o.jsx("div",{className:"flex items-end",children:o.jsxs(fe,{type:"button",className:"w-full flex items-center gap-2",onClick:I,disabled:n||ce.length===0||!R||!W,children:[o.jsx(Fs,{size:16}),"Əlavə et"]})})]})]})'

new = 'o.jsxs(o.Fragment,{children:[o.jsxs(Pt,{className:"p-6",children:[o.jsx("div",{className:"font-bold text-slate-900 mb-4",children:"Yeni material"}),o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-3 gap-4",children:[o.jsx(z,{label:"key (məs: banner_matt)",value:R,onChange:T=>{const N=T.target.value;H(N),J(W&&W!==R?W:N.replace(/_/g," ").replace(/\b\w/g,L=>L.toUpperCase()))}}),o.jsx(z,{label:"label",value:W,onChange:T=>J(T.target.value)}),o.jsx("div",{className:"flex items-end",children:o.jsxs(fe,{type:"button",className:"w-full flex items-center gap-2",onClick:I,disabled:n||ce.length===0||!R,children:[o.jsx(Fs,{size:16}),"Yarat"]})})]}),o.jsxs("div",{className:"mt-4",children:[o.jsx("div",{className:"text-sm font-bold text-slate-700 mb-2",children:"Printer seç"}),o.jsx("div",{className:"rounded-2xl border border-gray-200 bg-white px-4 py-3 max-h-48 overflow-y-auto space-y-2",children:d.filter(T=>Number((T==null?void 0:T.status)??1)===1).map(T=>{const N=String((T==null?void 0:T.price_key)??"").trim()||String((T==null?void 0:T.name)??"").trim();return o.jsxs("label",{className:"flex items-center gap-2 text-sm font-semibold text-slate-700",children:[o.jsx("input",{type:"checkbox",checked:ce.includes(N),onChange:L=>ee(w=>L.target.checked?w.includes(N)?w:[...w,N]:w.filter(O=>O!==N))}),o.jsx("span",{children:T.name})]},T.id)})})]})]}),o.jsxs(Pt,{className:"p-6 mt-4",children:[o.jsx("div",{className:"font-bold text-slate-900 mb-4",children:"Mövcud materialı printerə əlavə et"}),o.jsxs("div",{className:"grid grid-cols-1 md:grid-cols-4 gap-4",children:[o.jsxs("div",{className:"md:col-span-2",children:[o.jsx("div",{className:"text-sm font-bold text-slate-700 mb-2",children:"Mövcud material seç"}),o.jsxs("select",{className:"w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700",value:R,onChange:T=>{const N=T.target.value,L=p.find(w=>String((w==null?void 0:w.key)??"")===N);H(N),J(String((L==null?void 0:L.label)??N.replace(/_/g," ").replace(/\b\w/g,w=>w.toUpperCase())))},children:[o.jsx("option",{value:"",children:"Material seç"}),Array.from(new Map(p.map(T=>[String((T==null?void 0:T.key)??""),T]).filter(T=>T[0])).values()).map(T=>o.jsx("option",{value:T.key,children:T.label||T.key},T.key))]})]}),o.jsx(z,{label:"key",value:R,onChange:T=>H(T.target.value)}),o.jsx(z,{label:"label",value:W,onChange:T=>J(T.target.value)}),o.jsx("div",{className:"flex items-end",children:o.jsxs(fe,{type:"button",className:"w-full flex items-center gap-2",onClick:I,disabled:n||ce.length===0||!R,children:[o.jsx(Fs,{size:16}),"Əlavə et"]})})]})]})'

for path_str in paths:
    path = Path(path_str)
    s = path.read_text(encoding='utf-8')
    if old not in s:
        raise SystemExit(f'old snippet not found in {path_str}')
    s = s.replace(old, new, 1)
    path.write_text(s, encoding='utf-8')
    print('patched', path_str)
